const ActionTypes = {    
    RECEIVE_AUTH_TOKEN: 'RECEIVE_AUTH_TOKEN',
    RECEIVE_OVERVIEW: 'RECEIVE_OVERVIEW',
    RECEIVE_ALL_USERS: 'RECEIVE_ALL_USERS',
    RECEIVE_ALL_GROUPS: 'RECEIVE_ALL_GROUPS',
    RECEIVE_ALL_RESOURCES: 'RECEIVE_ALL_RESOURCES',
    RECEIVE_ALL_POLICIES: 'RECEIVE_ALL_POLICIES',
    RECEIVE_ALL_ROLES: 'RECEIVE_ALL_ROLES',        
  };
  
  export default ActionTypes;