const ActionTypes = {    
    RECEIVE_AUTH_TOKEN: 'RECEIVE_AUTH_TOKEN',
    RECEIVE_OVERVIEW: 'RECEIVE_OVERVIEW',
    RECEIVE_ALL_USERS: 'RECEIVE_ALL_USERS',
    RECEIVE_ALL_GROUPS: 'RECEIVE_ALL_GROUPS',        
  };
  
  export default ActionTypes;